plugins {
    id 'java'
    id 'application'
}

group = 'by.ezer'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    // Hibernate ORM 7.2 (включает JPA API)
    implementation 'org.hibernate.orm:hibernate-core:7.2.0.Final'

    // Явно JPA API (на случай проблем с импортами в IDE)
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'

    // PostgreSQL драйвер
    runtimeOnly 'org.postgresql:postgresql:42.7.3'

    // H2 база в памяти — для быстрого тестирования (очень удобно!)
    runtimeOnly 'com.h2database:h2:2.3.230'

    // Servlet API
    implementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'

    // Логирование
    implementation 'ch.qos.logback:logback-classic:1.5.16'

    //redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis:4.0.2'

    // Dotenv для .env файлов (если захочешь вынести credentials)
    implementation 'io.github.cdimascio:dotenv-java:3.0.2'

    //Spring boot + Security
    implementation 'org.springframework.boot:spring-boot:4.0.2'
    implementation 'org.springframework.boot:spring-boot-starter-web:4.0.2'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:4.0.2'
    implementation 'org.springframework.boot:spring-boot-starter-validation:4.0.2'
//    implementation 'org.springframework.boot:spring-boot-starter-data-redis:4.0.2'
    implementation 'org.springframework.boot:spring-boot-starter-security:4.0.2'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    // Jackson для JSON
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.40'
    annotationProcessor 'org.projectlombok:lombok:1.18.40'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    //MapStruct
    compileOnly 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    // Тесты
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'by.ezer.Main'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.compilerArgs << "-parameters"  // ← ВОТ ЭТО КРИТИЧЕСКОЕ
}